title: Alejandro Villarreal
description: Tango dancer, casual player of Magic: The Gathering, and amateur musician in permanent training. Fan of good food and of everything chocolate. In an eternal quest to become a gyroscope (i.e. as balanced a person as possible).
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
